jobs:
  main:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Pull Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./ci/verify

name: Run

on:
  schedule:
    - cron: "45 */3 * * *"
